name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.22'

      - name: Cache Bun cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache Turborepo outputs
        uses: actions/cache@v4
        with:
          path: |
            .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/bun.lockb', '**/turbo.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/bun.lockb') }}-
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Test (prefer turbo if available)
        shell: bash
        run: |
          set -euo pipefail
          if bun x turbo --version >/dev/null 2>&1; then
            bun x turbo run test --continue
          else
            bun test
          fi

